### ISSUE TITLE
How to post Issues

### ISSUE THREAD

**Issue by ScarecrowKrone** [ScarecrowKrone/MineTek#1]
This is the format you should be using to post a bug report. Standardizing bug reports will make it much MUCH easier to make use of them, and to answer your questions. You will not get official support from us if you fail to read this and follow the format. This is information we need.

IMPORTANT: When you run into a bug, quit the game immediately or in the case of a crash, do not reopen it. This will keep the most relevant information to the error at the end of the log.

When posting bugs, please try to keep to this format.

Single or Multiplayer:
Operating System:
Version of Java:
Pack version (specific numerical build number):
Description of problem:
Steps to reproduce problem (be very detailed here, I cannot help you if I cannot locate the root of the issue):
Crash/error report 

Crash reports are found in one of two places, if the crash happens before the pack has loaded (has not yet reached the main menu), the crash reports are found in the .technic/modpacks/minetek directory, and are generally called 'ForgeModLoader-client-{number}. Find the most recent one, and copy it over.

If the crash happens while the game is running, crash reports are found in the .technic/modpacks/minetek/crash-reports. Find the most recent one, and again, copy it over.

We cannot help you if you do not provide enough information.

**Comment by skwerlman** [comment]
I'm writing a file called CONTRIBUTING.md now. It will be autolinked when people try to create a new issue. When it is done, I will be closing this issue and #121, since it will contain the info from both of those.
