### ISSUE TITLE
List of known issues

### ISSUE THREAD

**Issue by skwerlman** [ScarecrowKrone/MineTek#121]
# Known Issues

##### Post all new issues in a new issue.
If you post it here, I promise I'll get really mad about it, and straight up delete your post.
* Once we've read your issue post, it will be copied into this one.
* Please keep all discussion regarding an issue in that issue's thread. It's okay to post in a closed thread.
* When an issue is resolved, it will be removed from this post.
* Please make certain you are not running Java 1.8. Minecraft is built against Java 1.6, and it's mostly coincidence that 1.7 is compatible. 1.8 is known to cause problems with Minecraft.
* As of Sun, Jan 23 2015, when someone says to update to the newest version of Java, they are referring to Java 1.7u76-b13. __*DO NOT USE JAVA 1.8.*__

### Regarding categories in this post:
* If an issue is listed as Reported, someone claims to have encountered the problem, but a dev has not yet confirmed the problem.
* If an issue is listed as Confirmed, someone claims to have encountered the problem, and a dev has replicated the problem.
* If an issue is listed as Possible, someone claims to have encountered the problem, but devs were unable to replicate the issue. This does not mean that the issue does not exist; we just haven't seen it.
* If an issue is listed as Intentional, it's not a bug, so don't report it.

# Entity and Biome Conflicts

These issues tend to be easy to fix, and usually won't be here for too long.

#### Reported Issues:
* None

#### Confirmed Issues:
* None

#### Possible Issues:
* None

#### Intentional:
* None

# Mod Interaction Bugs

These types of issues are, for the most part, very hard to fix, and may never end up fixed, since we don't control the source of the mods in the pack.

#### Reported Issues:
* None

#### Confirmed Issues:
* ForgeMultipart has a bug which can force users to suffer client-side crashes when using WR-CBE and Project Red. This has been traced to a version mismatch on the part of Project Red. See #195.

#### Possible Issues:
* None

#### Intentional:
* None

# Other Problems

These are you run-of-the-mill crashes. They tend to be issues with an individual mod, and aren't usually fixable by pack devs, aside from updating to newer versions.

#### Reported Issues:
* Client side crash when crafting tin wire or empty cells. Multiplayer only, seems to be a clash between IC2, Tinker's Construct and the generated GUI. Has not yet been replicated by @skwerlman or Scare. See #200.
* Client side crash on AMD GPUs when using Optifine. Devs cannot test as we only have nVidia GPUs. Potentially related to the `Advanced OpenGL` setting. See #208.

#### Confirmed Issues:
* Mekanism v7 (all current builds) has a faulty HashMap iteration bug, which can force the server to lag out, crash and/or time out all clients. Mekanism devs are aware. See #188.
* ComputerCraft monitors crash clients out when teleporting to an area with monitors present. Reported to dan200, see #178.

#### Possible Issues:
* None

#### Intentional:
* None

Last updated 2015-01-25

**Comment by ScarecrowKrone** [comment]
Finally updated! Three confirmed bugs, and one reported bug, not yet fixed (as far as has thus been investigated) as of build 2.8.7.

**Comment by skwerlman** [comment]
Added #208 to the list
updated recommended java version
switched date format at bottom to conform with [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601)
