### ISSUE TITLE
ComputerCraft monitors crash

### ISSUE THREAD

**Issue by CapnCinnamonBits** [ScarecrowKrone/MineTek#178]
-Multiplayer
-Windows 8.1
-Java 64bit
-2.6.7-Recommended
-Me and a friend were traveling and be both got to a point at which we both crash at the same time and every time we join the server MC will crash

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 11/28/14 6:56 PM
Description: Ticking screen

java.lang.NullPointerException: Ticking screen
	at net.minecraft.client.network.NetHandlerPlayClient.func_147281_a(NetHandlerPlayClient.java:744)
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:97)
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:15)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.network.NetHandlerPlayClient.func_147281_a(NetHandlerPlayClient.java:744)
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:97)
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:15)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)

-- Affected screen --
Details:
	Screen name: ~~ERROR~~ NullPointerException: null

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['CapnCinnamonBits'/381836, l='MpServer', x=-928.60, y=64.62, z=-2083.79]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-178,71,-499), Chunk: (at 14,4,13 in -12,-32; contains blocks -192,0,-512 to -177,255,-497), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 90411732 game time, 29913514 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 15 total; [EntityZombie['Zombie'/382123, l='MpServer', x=-913.47, y=40.00, z=-2104.06], EntityTFNagaSegment['unknown'/207, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/206, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/216, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/217, l='MpServer', x=0.00, y=0.00, z=0.00], EntityCreeper['Creeper'/382124, l='MpServer', x=-907.50, y=23.00, z=-2088.50], EntityTFNagaSegment['unknown'/212, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/213, l='MpServer', x=0.00, y=0.00, z=0.00], GCEntityClientPlayerMP['CapnCinnamonBits'/381836, l='MpServer', x=-928.60, y=64.62, z=-2083.79], EntityTFNagaSegment['unknown'/214, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/215, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/208, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/209, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/210, l='MpServer', x=0.00, y=0.00, z=0.00], EntityTFNagaSegment['unknown'/211, l='MpServer', x=0.00, y=0.00, z=0.00]]
	Retry entities: 0 total; []
	Server brand: cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.7.0_67, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 384471728 bytes (366 MB) / 1288175616 bytes (1228 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -XX:MaxPermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1232 Minecraft Forge 10.13.2.1232 Optifine OptiFine_1.7.10_HD_U_A4 119 mods loaded, 118 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.85.1232} [Forge Mod Loader] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.2.1232} [Minecraft Forge] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	appliedenergistics2-core{rv1-beta-37} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ImmibisMicroblocks{59.0.4} [Immibis's Microblocks] (immibis-microblocks-59.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MobiusCore{1.2.3} [MobiusCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NotEnoughItems{1.0.3.68} [Not Enough Items] (notenoughitems-1.7.10-1.0.3.68.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenEye{0.6} [OpenEye] (openeye-0.6-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	act{0.0.2a_1.7.10} [AdminCommandsToolbox] (act-0.0.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	IC2{2.2.654-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.654.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	advancedgenetics{1.5.7} [Advanced Genetics] (advanced-genetics-1.5.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ImmibisCore{59.0.4} [Immibis Core] (immibis-core-59.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AdvancedMachines{59.0.2} [Advanced Machines] (advanced-machines-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (advanced-solar-panels-1.7.10-3.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	appliedenergistics2{rv1-beta-37} [Applied Energistics 2] (applied-energistics-2-rv1-beta-37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CoFHCore{1.7.10R3.0.0B8} [CoFH Core] (cofhcore-3.0.0B8-36.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Core{6.2.0} [BuildCraft] (buildcraft-6.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (biomes-o-plenty-2.1.0.1019.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forestry{3.2.0.5} [Forestry for Minecraft] (forestry-1.7.10-3.2.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded{1.7.10R2.8.0RC5} [MineFactory Reloaded] (minefactory-reloaded-2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Baubles{1.0.1.8} [Baubles] (Baubles-1.7.10-1.0.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Thaumcraft{4.2.1.4} [Thaumcraft] (thaumcraft-1.7.10-4.2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Artifice{1.7.10R1.1.4} [Artifice] (artifice-1.7-1.1.4-300.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	asielib{0.3.1} [asielib] (AsieLib-1.7.10-0.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Backpack{2.0.0} [Backpack] (backpack-2.0.0-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	weaponmod{1.7.2 v1.14.2} [Balkon's WeaponMod] (balkons-weapon-mod-1.14.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	bdlib{1.5.1.32} [BD Lib] (bdlib-1.5.1.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BiblioCraft{1.9.1} [BiblioCraft] (bibliocraft-1.9.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Waila{1.5.3a} [Waila] (waila-1.7.10-1.5.3a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ResonantEngine{3.0.0} [Resonant Engine] (resonant-engine-3.0.0.307-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ForgeMultipart{1.1.0.314} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ResonantInductionCore{@MAJOR@.@MINOR@.@REVIS@} [Resonant Induction] (resonant-induction-0.3.4.234-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation] (thermal-foundation-1.0.0-b3-8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThermalExpansion{1.7.10R4.0.0B6} [Thermal Expansion] (thermal-expansion-4.0.0B6-16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BigReactors{0.4.0rc9} [Big Reactors] (big-reactors-0.4.0rc9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Transport{6.2.0} [BC Transport] (buildcraft-6.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Silicon{6.2.0} [BC Silicon] (buildcraft-6.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Builders{6.2.0} [BC Builders] (buildcraft-6.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Energy{6.2.0} [BC Energy] (buildcraft-6.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Factory{6.2.0} [BC Factory] (buildcraft-6.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CarpentersBlocks{3.3.3} [Carpenter's Blocks] (carpenters-blocks-3.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ComputerCraft{1.65} [ComputerCraft] (computercraft-1.65.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	eplus{3.0.2-d} [Enchanting Plus] (enchanting-plus-1.7.10-3.0.2-d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	EnderIO{1.7.10-2.2.1.276} [Ender IO] (enderio-1.7.10-2.2.1.276.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	EnderStorage{1.4.5.26} [EnderStorage] (enderstorage-1.7.10-1.4.5.26.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	extracells{2.1.13} [ExtraCells] (extra-cells-2.1.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ExtraUtilities{1.2.0} [Extra Utilities] (extra-utilities-1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	factorization.notify{1.0} [Factorization Notification System] (factorization-1.7.10-0.8.88.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	factorization{1.7.10-0.8.88.7} [Factorization] (factorization-1.7.10-0.8.88.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	factorization.misc{1.7.10-0.8.88.7} [Factorization Miscellaneous Nonsense] (factorization-1.7.10-0.8.88.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GalacticraftCore{3.0.6} [Galacticraft Core] (GalacticraftCore-1.7-3.0.6.232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GalacticraftMars{3.0.6} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.6.232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	gendustry{1.4.1.43} [GenDustry] (gendustry-1.4.1.43.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	HardcoreEnderExpansion{1.6.5} [Hardcore Ender Expansion] (hardcore-ender-expansion-1.6.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	iChunUtil{4.0.0} [iChunUtil] (ichun-util-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Hats{4.0.1} [Hats] (hats-4.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (ic2-gravisuite-1.7.10-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ImmibisPeripherals{59.0.2} [Immibis's Peripherals] (immibis-peripherals-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (inventory-tweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	JABBA{1.1.4} [JABBA] (jabba-1.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	LiquidXP{59.0.0} [Liquid XP] (liquid-xp-59.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Mantle{1.7.10-0.3.1.jenkins180} [Mantle] (mantle-1.7.10-0.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Railcraft{9.4.0.0} [Railcraft] (railcraft-1.7.10-9.4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Mekanism{7.1.1} [Mekanism] (mekanism-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MekanismGenerators{7.1.1} [MekanismGenerators] (MekanismGenerators-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MekanismTools{7.1.1} [MekanismTools] (MekanismTools-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MFFS{@MAJOR@.@MINOR@.@REVIS@} [Modular Force Field System] (mffs-4.1.0.44-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC5} [MFR Compat: Applied Energistics] (minefactory-reloaded-2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC4} [MFR Compat: Atum] (minefactory-reloaded-2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC5} [MFR Compat: BackTools] (minefactory-reloaded-2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC4} [MFR Compat: BuildCraft] (minefactory-reloaded-2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC4} [MFR Compat: Chococraft] (minefactory-reloaded-2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC4} [MFR Compat: ExtraBiomes] (minefactory-reloaded-2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC5} [MFR Compat: Forestry] (minefactory-reloaded-2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC4} [MFR Compat: ForgeMicroblock] (minefactory-reloaded-2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC4} [MFR Compat: IC2] (minefactory-reloaded-2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Mystcraft{0.11.0.00} [Mystcraft] (mystcraft-1.7.10-0.11.0.00.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC4} [MFR Compat: Mystcraft] (minefactory-reloaded-2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC4} [MFR Compat ProjectRed] (minefactory-reloaded-2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC4} [MFR Compat: Railcraft] (minefactory-reloaded-2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC4} [MFR Compat: RP2] (minefactory-reloaded-2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC4} [MFR Compat: Sufficient Biomes] (minefactory-reloaded-2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC5} [MFR Compat: Thaumcraft] (minefactory-reloaded-2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC4} [MFR Compat: Thermal Expansion] (minefactory-reloaded-2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	TwilightForest{2.3.2} [The Twilight Forest] (twilight-forest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC5} [MFR Compat: TwilightForest] (minefactory-reloaded-2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC5} [MFR Compat: Vanilla] (minefactory-reloaded-2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Morph{0.9.0} [Morph] (morph-0.9.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NetherOres{1.7.10R2.3.0RC3} [Nether Ores] (nether-ores-2.3.0-rc3-84.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenMods{0.6} [OpenMods] (open-mods-lib-1.7.10-0.6-snapshot-264.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenBlocks{1.3} [OpenBlocks] (open-blocks-1.7.10-1.3-snapshot-502.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OpenComputers{1.4.1.14} [OpenComputers] (open-computers-1.7.10-1.4.1.14-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	planetguyLib{1.3} [planetguyLib] (PlanetguyLib-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	PneumaticCraft{1.2.6} [PneumaticCraft] (pneumatic-craft-1.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	JAKJ_RedstoneInMotion{2.2.0} [Remain In Motion] (RemainInMotion-2.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	JAKJ_RedstoneInMotion_HollowCarriages{1.0} [JAKJ_RedstoneInMotion_HollowCarriages] (RemainInMotion-2.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	SSR{rc3} [Soul Shards Reborn] (soul-shards-reborn-rc3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	statues{2.1.4} [Statues] (statues-1.7.10-2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	StevesCarts{2.0.0.b18} [Steve's Carts 2] (stevescarts2-0.0.b18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Sync{4.0.0} [Sync] (sync-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ThaumicTinkerer{2.5-1.7.10-156} [Thaumic Tinkerer] (thaumic-tinkerer-2.5-1.7.10-156.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct] (tinkers-construct-1.7.10-1.6.0.d40.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	TooManyGodDamnOres{${version}} [TooManyGodDamnOres] (too-many-god-damn-ores-1.4-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Translocator{1.1.1.13} [Translocator] (translocator-1.7.10-1.1.1.13-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Treecapitator{1.7.2} [Treecapitator] (treecapitator-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Tubestuff{59.0.1} [Tubestuff] (tubestuff-59.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (wr-cbe-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (wr-cbe-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (wr-cbe-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	McMultipart{1.1.0.314} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ForgeMicroblock{1.1.0.314} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	asielibcore{} [AsieLib CoreMod] (minecraft.jar) Unloaded->Disabled
	OpenModsLib crash transformers: [gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED],[map_gen_fix:FINISHED],[movement_callback:FINISHED],[stencil_patches:FINISHED]
	AE2 Version: beta rv1-beta-37 for Forge 10.13.0.1187
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	Stencil buffer state: Function set: GL30, pool: internal, bits: 8
	Forestry : [Forestry] Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:ON, MJ6:OFF, MJ5:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:ON, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:ON, BetterStorage:OFF
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 3.1.0 - Build 9.17.10.3347, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by ScarecrowKrone** [comment]
Has this been reported/is this still an issue @skwerlman?

**Comment by skwerlman** [comment]
As mentioned in our conversation, it has been reported, but I have not seen any progress on it.

**Comment by skwerlman** [comment]
Looking back at this crash, it looks like a Twilight Forest crash, not a CC crash...
`Ticking Screen` is a generic rendering error, and there's no mention of CC in the stacktraces.
Since TF has updated since this crash, I think we can assume its safe to close.
