### ISSUE TITLE
Server Timing Out

### ISSUE THREAD

**Issue by cypherkaldarese** [ScarecrowKrone/MineTek#188]
I am not sure what the issue is, but inevitably every time I play recently i will be able to play normally for maybe 10 or 15 minutes, and then all of a sudden no chests will open, no blocks will break, no doors will open and I cannot access any of my machines, and soon there after I will be kicked from the server with an error message. Then when i try to log back in I get almost exactly the same message each and every time I try, it reads: "Failed to connect to the server Timed Out" In each case I am kicked from the server because of the "Timed Out" error. The only thing that seems to solve it is time. I didn't see this in the "known issues" area, and several others have reported it as well. is my residence too far out maybe for the server to handle (I don't think it is even that far out). HELP!? I really would love to get back on and join ya'll!

edit: Just noticed that in the game itself, the server shows online with 10 people in game. But the website shows that the server is offline.

**Comment by ScarecrowKrone** [comment]
I have finally identified a potential cause of this issue - there is quite a severe bug in a HashMap implementation in Mekanism v7. Authors are aware, and we are working with them to fix this.

**Comment by ScarecrowKrone** [comment]
Will be fixed in MineTek 3.
