### ISSUE TITLE
Crash in Gnomes base

### ISSUE THREAD

**Issue by Biteboy5** [ScarecrowKrone/MineTek#195]
Single or Multiplayer:  Multiplayer
Operating System: Windows 7
Version of Java: Java 7 update 71
Pack version (specific numerical build number): 2.8.3
Description of problem: It comes up with  'A fatal error has occured. connection is terminated.'

Steps to reproduce problem (be very detailed here, I cannot help you if I cannot locate the root of the issue):  Go to coordinates +863 70 +6
Crash/error report
http://paste.ubuntu.com/9599983/

**Comment by ScarecrowKrone** [comment]
Fixed as of 2.9.1.
