### ISSUE TITLE
Bugged Crafting Recipie For Solar Helmits

### ISSUE THREAD

**Issue by bradcarnage** [ScarecrowKrone/MineTek#205]
1. Multiplayer (play.mintekmc.com)
2. Linux Xubuntu
3. java version "1.7.0_72"
Java(TM) SE Runtime Environment (build 1.7.0_72-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.72-b04, mixed mode)
4. 2.8.7 (Recommended)
5. Bugged Crafting Recipie For Solar Helmits

Video: https://www.youtube.com/watch?v=Z6dSkU16k78

**Comment by skwerlman** [comment]
This looks like the typical rubber-banding one would expect from a server under a lot of strain. Can you test in single player?

**Comment by bradcarnage** [comment]
Well, i originally had my ae system try and craft it.. and it kinda did the same thing.
It just said "Scheduled" and not "Crafting" at the end

**Comment by skwerlman** [comment]
In single player?

**Comment by bradcarnage** [comment]
ok, i found the main bug in sinleplayer after i tested some more.
Video: http://youtu.be/HaE3cCR5vGE

**Comment by skwerlman** [comment]
please reopen if this is still an issue in MT3
