### ISSUE TITLE
Barely any Fire Flower Seeds Spawning in the nether

### ISSUE THREAD

**Issue by bradcarnage** [ScarecrowKrone/MineTek#206]
1. Multiplayer (play.mintekmc.com)
2. Linux Xubuntu
3. java version "1.7.0_72" Java(TM) SE Runtime Environment (build 1.7.0_72-b14) Java HotSpot(TM) 64-Bit Server VM (build 24.72-b04, mixed mode)
4. 2.8.7 (Recommended)
5. No Fire Flower Seeds Spawning in the nether
6. the item id is 5365:1

**Comment by skwerlman** [comment]
Does this also happen in single player?

**Comment by bradcarnage** [comment]
Nevermind. Just VERY rare

**Comment by skwerlman** [comment]
Please close this issue.
