### ISSUE TITLE
Server Hung microblocks and Proj Red wires 

### ISSUE THREAD

**Issue by tslippy** [ScarecrowKrone/MineTek#207]
Whenever I put a cover strip and a red alloy wire in the same block, the server becomes unresponsive in the console, and blocks are unable to be broken.  Eventually leading to killing the server process and restarting. Server version 2.8.7

**Comment by ScarecrowKrone** [comment]
We need more information from you. Server OS, Java version and type, allocated RAM etc.

**Comment by skwerlman** [comment]
Logs would also help

**Comment by tslippy** [comment]
I'm using creeperhost.net with 2.5GB allocated. Only two players are ever on at a time, and everything usually works. I believe Creeperhost.net uses Java 1.8 on a Linux operating system. Server logs are not generated.

I have done some troubleshooting and it seems that it is also related to AE2.I had put a level emitter and red alloy wire in the same block, then put a cover strip in the block in front of the level emitter, then put a red alloy wire in the block in front of the level emitter (the same block as the second red alloy wire). This is what causes the issue, and even hangs the internal server in my SP world on windows 7 with 4GB RAM allocated running on Java 1.7.

**Comment by ScarecrowKrone** [comment]
I will do some testing, and you are incorrect in stating that server logs aren't generated. Unless you intentionally turn logging off (it's on by default) then logs are created. We need to see them, they are located in the logs folder of your server root.

**Comment by tslippy** [comment]
Ok yes. What I meant was that no crash report is generated and the server log is not updated. The last chat message before the server hangs is all that shows up. I'll try again and see if I can get a server log.

**Comment by skwerlman** [comment]
Also, could you try to find out which distro (Debian, Ubuntu, CentOS, RHEL, etc.) and version of linux is being used? Linux is a very large category.

If you have access to a terminal, the output of `uname -oprsv` will provide all the necessary info regarding the OS.

**Comment by tslippy** [comment]
The result of the 'uname -oprsv' command is: Linux 2.6.32-042stab075.2 #1 SMP Tue Mar 5 15:21:53 MSK 2013 x86_64 GNU/Linux

**Comment by tslippy** [comment]
Also,  'java -version' gives:
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)

**Comment by tslippy** [comment]
Also note that I said earlier that this exact problem occurs in Single Player on my Windows 7 machine running Java 1.7, so it seems to be unrelated to the server OS or java version.

**Comment by skwerlman** [comment]
@ScarecrowKrone: has this been confirmed yet? If not, I'll do some testing today.

**Comment by ScarecrowKrone** [comment]
FIxed as of 3.0.3.
