### ISSUE TITLE
Crashing About Every 5 Minutes In Server

### ISSUE THREAD

**Issue by OmegaInferno49** [ScarecrowKrone/MineTek#211]
Single or Multiplayer: Multiplayer

Operating System: Windows 8.1

Version of Java: Latest - 1.8.0_31
java version "1.8.0_31"
Java<TM> SE Runtime Environment <build 1.8.0_31-b13>
Java HotSpot<TM> 64-Bit Server UM <build 25.31-b07, mixed mode>

Pack version: Latest - 3.0.7

Description of problem: Upon joining the server I started to crash within' a certain amount of time depending on what I have my FPS set to, the lower the more time it'll take to crash.

Steps to reproduce problem:
Not reproducible due to random crash.

Crash/error report:
http://paste.ubuntu.com/10258934/

**Comment by skwerlman** [comment]
This is unfortunately a rather generic crash, so it may take some time to figure out.

**Comment by skwerlman** [comment]
Best guess so far is some sort of interaction between Optifine, Technic and your AMD graphics card.

**Comment by ScarecrowKrone** [comment]
I can confirm it is an Optifine thing. Disable Connected Textures and Advanced OpenGL.

**Comment by skwerlman** [comment]
I'll add this to known issues and close.
