### ISSUE TITLE
Bad performance when running pack

### ISSUE THREAD

**Issue by WiIdcard** [ScarecrowKrone/MineTek#212]
I don't know if this is the right place for it but I'm gonna try anyway. 

While running the pack I have terrible performance. My RAM usage gets maxed out at 98%+ and it leaves me unable to run any other programs in the background. After closing the pack as well I'm left unable to use my computer for 5 or so minutes as everything runs slowly.

This is strange since I have 8GB or RAM and have heard someone can run on the same render distance and settings as me with only 5GB of RAM. My CPU usage isnt an issue as this is usually no higher than 60 or 70%.

My physical memory usage is usually quite high (65%) even with not many programs open. However I've heard this is normal (http://www.tomshardware.co.uk/forum/2185-63-windows-idle, second post down) so I do not know if this is the issue. It'd be nice to have better performance and be able to tab out etc so if you could help that would be great thanks!

My system specs: 
Operating System - Windows 7 Home Premium 64-bit (6.1, Build 7601)
Processor - AMD A10-5800k APU with Radeon HD Graphics (4CPUs), ~3.8GHz
Memory - 8192MB RAM
Page file - 20912MB used, 6000MB available 
DirectX Version: DirectX 11 
Graphics Card - NVIDIA GeForce GTX 650
Approx. Total Memory: 4038 MB
Current Display Mode: 1920x1080 (32bit) (60Hz)

Crash reports: None, N/A

**Comment by ScarecrowKrone** [comment]
You may have 8 GB of RAM but have you actually allocated it to the pack? You need to go into launcher options and allocated at least 3-4 GB of RAM. Otherwise, any performance issues you have are not related to us.

**Comment by WiIdcard** [comment]
Indeed I have 5GB's of RAM allocated. Like I said its not a performance issue within the pack itself. The pack runs fine on a solid fps but it hogs up resources and makes me unable to use any other programs while playing nor for a while after closing the pack. my Advanced OpenGL is enabled already and like I said it isnt a problem with CPU usage.

The main problem is the fact I am getting more resource usage for the same performance as others, and It'd be nice to be able to tab out to look at wikis etc while playing the pack, which currently I am unable to do.

Thanks for your help btw :)

**Comment by ScarecrowKrone** [comment]
Its something with your system, possibly with your Java. Please report back with the EXACT version of the Java VM you are using. I know what you mean by being a resource hog; I personally notice a difference when using MineTek and other programs simultaneously, but with multiple monitors and my beastly computer the difference isn't much for me. It also might be an AMD thing (lots of AMD users have issues with OpenGL, haven't a clue why), in which case ye be boned. Try reducing the allocation from 5 to 4 GB, and that'll improve the performance of exterior programs when running MineTek.

**Comment by WiIdcard** [comment]
Ok I'll try that! My exact Java version is Version 7 Update 60 (build 1.7.0_60-b19) 64-bit version only (no 32 bit version) I know Java 8 is out but I deliberatly got Java 7 because mods dont seem to like Java 8 sometimes

**Comment by ScarecrowKrone** [comment]
Unable to replicate. Closed.
