### ISSUE TITLE
Think I did it again

### ISSUE THREAD

**Issue by Mirvanna** [ScarecrowKrone/MineTek#214]
Once again, I think I broke the server. Using a machine what it is for.

OpenBlocks 'Block Breaker' equipped it with a obsidian axe and sat some spruce planks in front, server died as I attached the chest (a inventory for it to deposit into and start working).

**Comment by Mirvanna** [comment]
So far unable to replicate in SP, may only occur in MP... testing different blocks within the same chunk that may have caused the crash. One other player was online, but I forget the name.

**Comment by ScarecrowKrone** [comment]
I think the best option would be to not do it while I look into fixing OpenBlocks.

**Comment by ScarecrowKrone** [comment]
This needs to be tested on the server @skwerlman

**Comment by skwerlman** [comment]
will check later today

**Comment by ScarecrowKrone** [comment]
LONG SINCE FIXED.
