### ISSUE TITLE
MineTek 3.1 Update

### ISSUE THREAD

**Issue by ScarecrowKrone** [ScarecrowKrone/MineTek#215]
Update to the modpack includes:

- [x] Version update for all mods if possible.
- [x] Optimization of modpack.
- [x] Config options.
- [x] Server files.
 - [x] Refactor permissions.yml (I'll take care of this tonight - @skwerlman)
 - [x] Update banned item list to use 1.7 block ID's and not numerical ID's. @skwerlman 

I will comment when tasks are completed.

**Comment by skwerlman** [comment]
Seemed like a perfect time to use a [task list](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown), so I edited your post.

**Comment by skwerlman** [comment]
Finished permissions refactor yesterday

**Comment by ScarecrowKrone** [comment]
I've begun 1 and 2; I've already identified several areas of potential improvement.
