### ISSUE TITLE
Crash Report With RIM

### ISSUE THREAD

**Issue by bradcarnage** [ScarecrowKrone/MineTek#218]
Single or Multiplayer: Both - Singleplayer this time

Operating System: Windows 10 Pro Technical Preveiw - Evalution copy - Build 9926

Version of Java: java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)

Pack version: 3.1.4

Description of problem:
Client Crashes Every time RIM Moves a Frame

Crash Report: http://pastebin.com/kGjibh9j

Forge Log: http://pastebin.com/R68EyGUJ

**Comment by ScarecrowKrone** [comment]
This is not a standard crash report. Minecraft hasn't crashed, the Java VM has, which shouldn't happen at all. In which case, I am minded to believe this is something on your side that's broken. Try updating your LWJGL, your graphics card drivers etc while I look into this.

**Comment by skwerlman** [comment]
I was just reading through the crash log again, and it says you're on win8.1b9600, which is obviously not win10b9926.
Also, it says it crashed inside of a C DLL named "ig75icd64.dll", which makes this a driver crash on your end. Update your graphics drivers.
