### ISSUE TITLE
Server Problems (Starting Up)

### ISSUE THREAD

**Issue by EthanAustin** [ScarecrowKrone/MineTek#220]
When I load up my Minetek 3 server, it fails to work.
It is on a host such as MCPH.

Here is some console log

27.03 19:04:51 [multicraft] Server stopped
27.03 19:04:51 [multicraft] Server shut down
27.03 19:04:50 [server] INFO [19:04:50 info]: The state engine was in incorrect state CONSTRUCTING and forced into state SERVER_STOPPED. Errors may have been discarded.
27.03 19:04:50 [server] INFO [19:04:50 info]: Holder lookups applied
27.03 19:04:50 [server] INFO [19:04:50 info]: Applying holder lookups
27.03 19:04:50 [server] INFO [19:04:50 warn]: Can't revert to frozen GameData state without freezing first.
27.03 19:04:50 [server] INFO [19:04:50 error]: This crash report has been saved to: /./crash-reports/crash-2015-03-27_19.04.50-server.txt
27.03 19:04:50 [server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]
27.03 19:04:50 [server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [minecraftserver.class:?]
27.03 19:04:50 [server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:170) ~[lt.class:?]
27.03 19:04:50 [server] INFO at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:318) ~[fmlcommonhandler.class:git-cauldron-mcpc-plus-1.7.10-1.1231.01.207]
27.03 19:04:50 [server] INFO at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) ~[fmlserverhandler.class:git-cauldron-mcpc-plus-1.7.10-1.1231.01.207]
27.03 19:04:50 [server] INFO at cpw.mods.fml.common.Loader.loadMods(Loader.java:472) ~[loader.class:git-cauldron-mcpc-plus-1.7.10-1.1231.01.207]
27.03 19:04:50 [server] INFO at cpw.mods.fml.common.Loader.sortModList(Loader.java:227) ~[loader.class:git-cauldron-mcpc-plus-1.7.10-1.1231.01.207]
27.03 19:04:50 [server] INFO cpw.mods.fml.common.MissingModsException
27.03 19:04:50 [server] INFO [19:04:50 error]: Encountered an unexpected exception
27.03 19:04:50 [server] INFO [19:04:50 error]: The mod bluepower (Blue Power) requires mods [qmunitylib] to be available
27.03 19:04:49 [server] INFO [19:04:49 info]: Found mod(s) [extrautilities] containing declared API package baubles.api (owned by Baubles) without associated API reference
27.03 19:04:49 [server] INFO [19:04:49 info]: Found mod(s) [gravisuite] containing declared API package buildcraft.api.tools (owned by BuildCraftAPI|core) without associated API reference
27.03 19:04:49 [server] INFO [19:04:49 info]: Forge Mod Loader has identified 131 mods to load
27.03 19:04:49 [server] INFO [19:04:49 warn]: Mod MrTJPCoreMod is missing the required element 'version' and no fallback can be found. Substituting '1.0'.
27.03 19:04:49 [server] INFO [19:04:49 info]: Mod MrTJPCoreMod is missing the required element 'name'. Substituting MrTJPCoreMod
27.03 19:04:49 [server] INFO [19:04:49 warn]: Mod McMultipart is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.1.0.314
27.03 19:04:49 [server] INFO [19:04:49 warn]: Mod ForgeMultipart is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.1.0.314
27.03 19:04:49 [multicraft] Skipped 12 lines due to rate limit (30/s)
27.03 19:04:49 [server] INFO at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403) ~[jsonreader.class:?]
27.03 19:04:49 [server] INFO at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:494) ~[jsonreader.class:?]
27.03 19:04:49 [server] INFO at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[jsonreader.class:?]
27.03 19:04:49 [server] INFO Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 10 column 2
27.03 19:04:49 [server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]
27.03 19:04:49 [server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [minecraftserver.class:?]
27.03 19:04:49 [server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:170) [lt.class:?]
27.03 19:04:49 [server] INFO at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:318) [fmlcommonhandler.class:git-cauldron-mcpc-plus-1.7.10-1.1231.01.207]
27.03 19:04:49 [server] INFO at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) [fmlserverhandler.class:git-cauldron-mcpc-plus-1.7.10-1.1231.01.207]
27.03 19:04:49 [server] INFO at cpw.mods.fml.common.Loader.loadMods(Loader.java:468) [loader.class:git-cauldron-mcpc-plus-1.7.10-1.1231.01.207]
27.03 19:04:49 [server] INFO at cpw.mods.fml.common.Loader.identifyMods(Loader.java:347) [loader.class:git-cauldron-mcpc-plus-1.7.10-1.1231.01.207]
27.03 19:04:49 [server] INFO at cpw.mods.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:127) [moddiscoverer.class:git-cauldron-mcpc-plus-1.7.10-1.1231.01.207]
27.03 19:04:49 [server] INFO at cpw.mods.fml.common.discovery.ModCandidate.explore(ModCandidate.java:71) [modcandidate.class:git-cauldron-mcpc-plus-1.7.10-1.1231.01.207]
27.03 19:04:49 [server] INFO at cpw.mods.fml.common.discovery.ContainerType.findMods(ContainerType.java:42) [containertype.class:git-cauldron-mcpc-plus-1.7.10-1.1231.01.207]
27.03 19:04:49 [server] INFO at cpw.mods.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:53) [jardiscoverer.class:git-cauldron-mcpc-plus-1.7.10-1.1231.01.207]
27.03 19:04:49 [server] INFO at cpw.mods.fml.common.MetadataCollection.from(MetadataCollection.java:55) [metadatacollection.class:git-cauldron-mcpc-plus-1.7.10-1.1231.01.207]
27.03 19:04:49 [server] INFO at com.google.gson.JsonParser.parse(JsonParser.java:59) ~[jsonparser.class:?]
27.03 19:04:49 [server] INFO at com.google.gson.JsonParser.parse(JsonParser.java:84) ~[jsonparser.class:?]
27.03 19:04:49 [server] INFO at com.google.gson.internal.Streams.parse(Streams.java:56) ~[streams.class:?]
27.03 19:04:49 [server] INFO com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 10 column 2
27.03 19:04:49 [server] INFO [19:04:49 error]: The mcmod.info file in RemainInMotion-2.2.0.jar cannot be parsed as valid JSON. It will be ignored
27.03 19:04:49 [server] INFO [19:04:49 warn]: Mod ProjRed|Exploration is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 4.5.8.59
27.03 19:04:49 [server] INFO [19:04:49 warn]: Mod ProjRed|Transportation is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 4.5.8.59
27.03 19:04:49 [server] INFO [19:04:49 warn]: Mod ProjRed|Expansion is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 4.5.8.59
27.03 19:04:49 [server] INFO [19:04:49 warn]: Mod ProjRed|Illumination is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 4.5.8.59
27.03 19:04:49 [server] INFO [19:04:49 warn]: Mod ProjRed|Transmission is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 4.5.8.59
27.03 19:04:49 [server] INFO [19:04:49 warn]: Mod ProjRed|Integration is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 4.5.8.59
27.03 19:04:49 [server] INFO [19:04:49 warn]: Mod ProjRed|Compatibility is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 4.5.8.59
27.03 19:04:49 [server] INFO [19:04:49 warn]: Mod ProjRed|Core is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 4.5.8.59
27.03 19:04:48 [server] INFO [19:04:48 info]: Mod planetguyLib is missing the required element 'name'. Substituting planetguyLib
27.03 19:04:47 [server] INFO [19:04:47 warn]: Mod ExtraUtilities is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.2.0
27.03 19:04:47 [server] INFO [19:04:47 warn]: Mod EnderStorage is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.4.5.27
27.03 19:04:47 [server] INFO [19:04:47 warn]: Mod ChickenChunks is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.3.4.16
27.03 19:04:47 [multicraft] Skipped 41 lines due to rate limit (30/s)
27.03 19:04:45 [server] INFO [19:04:37 info]: [micdoodle8.mods.miccore.micdoodleplugin:injectdata:292]: [micdoodle8core]: Patching game...
27.03 19:04:45 [server] INFO [19:04:37 info]: [micdoodle8.mods.miccore.micdoodleplugin:injectdata:292]: [micdoodle8core]: Patching game...
27.03 19:04:45 [server] INFO [19:04:37 info]: [micdoodle8.mods.miccore.micdoodleplugin:getasmtransformerclass:104]: Successfully Registered Transformer
27.03 19:04:45 [server] INFO [19:04:37 info]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
27.03 19:04:45 [server] INFO [19:04:37 info]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
27.03 19:04:45 [server] INFO [19:04:37 info]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
27.03 19:04:45 [server] INFO [19:04:37 info]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
27.03 19:04:45 [server] INFO [19:04:37 info]: Loaded library ejml-0.23.jar.
27.03 19:04:45 [server] INFO [19:04:37 info]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
27.03 19:04:45 [server] INFO [19:04:37 info]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
27.03 19:04:45 [server] INFO [19:04:37 info]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
27.03 19:04:45 [server] INFO [19:04:37 info]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
27.03 19:04:45 [server] INFO [19:04:37 info]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
27.03 19:04:45 [server] INFO [19:04:37 info]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
27.03 19:04:45 [server] INFO [19:04:37 info]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
27.03 19:04:45 [server] INFO [19:04:37 info]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
27.03 19:04:45 [server] INFO [19:04:36 info]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
27.03 19:04:45 [server] INFO [19:04:36 info]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
27.03 19:04:45 [server] INFO [19:04:36 info]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
27.03 19:04:45 [server] INFO [19:04:36 info]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
27.03 19:04:45 [server] INFO [19:04:36 info]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
27.03 19:04:45 [server] INFO [19:04:36 warn]: Missing @MCVersion: codechicken.core.launch.CodeChickenCorePlugin cofh.asm.LoadingPlugin codechicken.core.launch.DepLoader mods.immibis.microblocks.coremod.MicroblocksCoreMod ic2.core.coremod.IC2core invtweaks.forge.asm.FMLPlugin logisticspipes.asm.LogisticsPipesCoreLoader mekanism.common.asm.LoadingHook micdoodle8.mods.miccore.MicdoodlePlugin mcp.mobius.mobiuscore.asm.CoreDescription mrtjp.core.handler.CorePlugin codechicken.nei.asm.NEICorePlugin openblocks.OpenBlocksCorePlugin openmods.OpenModsCorePlugin openeye.CorePlugin codechicken.core.launch.DepLoader codechicken.core.launch.DepLoader thaumcraft.codechicken.core.launch.DepLoader thaumic.tinkerer.preloader.ThaumicTLoaderContainer codechicken.core.launch.DepLoader
27.03 19:04:45 [server] INFO [19:04:36 warn]: The following coremods do not have a @MCVersion annotation. They may cause problems if this is not the correct version of Minecraft for them.
27.03 19:04:45 [server] INFO [19:04:36 info]: [codechicken.core.launch.deploader$deploadinst:checkexisting:436]: Warning: version of bspkrsCore, 6.15 is newer than request 6.9
27.03 19:04:45 [server] INFO [19:04:33 info]: [appeng] Core Init
27.03 19:04:45 [server] INFO [19:04:33 info]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_05, running on Linux:amd64:3.10.23-xxxx-std-ipv6-64, installed at /usr/java/jre1.8.0_05
27.03 19:04:45 [server] INFO [19:04:33 info]: Forge Mod Loader version 7.10.85.1231 for Minecraft 1.7.10 loading
27.03 19:04:45 [server] INFO [19:04:33 info]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
27.03 19:04:45 [server] INFO [19:04:33 info]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
27.03 19:04:45 [server] INFO [19:04:33 info]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
27.03 19:04:43 [server] INFO [mobiuscore] Successful injection in h ()V
27.03 19:04:43 [server] INFO [mobiuscore] Successful injection in h ()V
27.03 19:04:43 [server] INFO [mobiuscore] Successful injection in h ()V
27.03 19:04:43 [server] INFO [mobiuscore] Successful injection in h ()V
27.03 19:04:43 [server] INFO [mobiuscore] Found World.updateEntities()...
27.03 19:04:43 [server] INFO [mobiuscore] Found net.minecraft.world.World [ ahb ] with checksum E5F84E145DDA65904719ACAA96BE6034
27.03 19:04:43 [server] INFO [mobiuscore] Switching injection mode to CAULDRON
27.03 19:04:43 [server] INFO [mobiuscore] Successful injection in onPostWorldTick (Lahb;)V
27.03 19:04:43 [server] INFO [mobiuscore] Successful injection in onPreWorldTick (Lahb;)V
27.03 19:04:43 [server] INFO [mobiuscore] Successful injection in onPostServerTick ()V
27.03 19:04:43 [server] INFO [mobiuscore] Successful injection in onPreServerTick ()V
27.03 19:04:43 [server] INFO [mobiuscore] Found cpw.mods.fml.common.FMLCommonHandler with checksum D780DC65E1A5B3D3F05CB60819BDE46C
27.03 19:04:43 [server] INFO [mobiuscore] Successful injection in b ()V
27.03 19:04:43 [server] INFO [mobiuscore] Successful injection in b ()V
27.03 19:04:43 [server] INFO [mobiuscore] Found net.minecraft.world.WorldServer [ mt ] with checksum 37BCC3E32F530AEF30C2D8DFFBBFF4F7
27.03 19:04:43 [server] INFO [mobiuscore] Current code is OBFUSCATED
27.03 19:04:33 [multicraft] Stopping server!
27.03 19:04:33 [multicraft] Received stop command
27.03 19:04:30 [multicraft] Loaded config for "Default"
27.03 19:04:30 [multicraft] Starting server!
27.03 19:04:30 [multicraft] Loading server properties

**Comment by ScarecrowKrone** [comment]
Basically, you ignored the guidelines for contributing and posted the same thing as you did on the forums. Please post all the details, plus the crash report, I need or I'll tag this as invalid and ignore it. See https://github.com/ScarecrowKrone/MineTek/blob/master/CONTRIBUTING.md for details.
